### ISSUE TITLE
Structure_Engine: Ensure setting edge geometry and panel/opening edges returns an object with new Guid

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM_Engine#1001]

**Comment by rwemay** [comment]
@IsakNaslundBh  Is it possible to close this this week? Should be a very minor change. I can push commits into a PR or create one, and link to test file, if necessary.

**Comment by IsakNaslundBh** [comment]
I do not have any planned work on Structure_Engine this week. Eduardo has some changes in the Structure_Engine though, but should be closed out today ideally, after that should be free.

Good to have a chat about what this means from a framework point of view as well though, as philosophically updating the GUID when setting geometry then will mean "This is a new object". Could argue both ways, depending on the case for this.. @al-fisher

**Comment by rwemay** [comment]
The specific need for these at the moment is on some ‘translate’ methods. If this is a longer term issue, is it possible for us to modify the translate methods so they still call these modifiers but then add a ‘manual’ new guid method at the translate/toolkit end?

**Comment by al-fisher** [comment]
> philosophically updating the GUID when setting geometry then will mean "This is a new object"

@IsakNaslundBh on your point above. I think this is the case. Any modification - should be returning a new object currently. Is simpler for us to have a clear cut approach to immutability now - to also ensure we are getting expected behaviour in the flow-based programming environment.

Agree @IsakNaslundBh - room for more sophisciated handling of cloning to not (necessarily) duplicate/create new objects everytime. However - big subject to be handled more generally later.

I would therefore suggest modifying to return new GUID now.
@rwemay FYI

**Comment by IsakNaslundBh** [comment]
@al-fisher I think there are cases I was thinking of where it is not as clear-cut to me whether it should be a "new" object or not even for translate. Say you need to move the whole building 100 m in x direction for whatever reason, then you still might want to see the original and the new objects as "The same" but moved.
But can ofc argue another case where you want to array out some walls/floors using translate where you will want the objects to be separate new objects.

This is my only reason for slight caution about it, but with that said, I am ok with updating the SetGeometry methods to update the GUIDs.
@rwemay FYI
