### ISSUE TITLE
Environment_Engine: Add DisplayNormal method

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1063]
Add method to `DisplayNormal` for 2DElements

![image](https://user-images.githubusercontent.com/26113670/60199934-e8a38100-983c-11e9-915c-031de879671d.png)

**Comment by FraserGreenroyd** [comment]
Having thought about this, I'm not sure that a `DisplayNormal` method brings any benefit to BHoM - the workflow described in your image is a perfect example of BHoM interopping nicely with the native components of the chosen UI (in this case Grasshopper), which is something BHoM fundamentally wants to achieve. Otherwise we'd be rewriting the UI engines which provide a lot of good stuff for us. So in this instance, I'm going to leave this as is - with us mixing and matching the best available components from GH/Dynamo/Excel/other UIs to produce powerful computation :smile:
