### ISSUE TITLE
Geometry_Engine: PlanarSurface error

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1145]
#### Description:

I come across that now all PlanarSurface are generated from closed Polyline, this is causing false impression that surfaces are missing
![image](https://user-images.githubusercontent.com/26113670/63506750-10763480-c4ce-11e9-8325-04adaf763c9b.png)

#### How to replicate:

run script

#### Expected behaviour:

to see this
![image](https://user-images.githubusercontent.com/26113670/63507181-0d2f7880-c4cf-11e9-9058-d532e16130d1.png)

#### Test file(s):

[test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/BHoM_Engine_Issue1145-PlanarSurface?csf=1&e=afcucX)

**Comment by kThorsager** [comment]
Hi, @michaldengusiak 

Gave this a fresh test and seems to be working
![image](https://user-images.githubusercontent.com/53530468/80792056-676af800-8b8b-11ea-8306-96ee3eb87f65.png)
Had to update the test file due to this being very old, but think this has been resolved?
[New test file in the same folder](https://burohappold.sharepoint.com/:f:/s/BHoM/EuyABzkRJaVEoAtGteIlX2cBTX2U7ojoaMsQdcisbPbpYw?e=0Gtnog)

**Comment by michaldengusiak** [comment]
perfect is working correctly now,
