### ISSUE TITLE
Physical_Engine: Modify AddFragments

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1184]
#### Description:

As per our [discussion](https://github.com/BHoM/BHoM/issues/553), I am creating a method to `AddFragments` to PhysicalElements

**Comment by FraserGreenroyd** [comment]
@michaldengusiak the implementation you've done in the PR is not the right implementation. This is why issues should be discussed at least in some small detail either on GitHub, or offline and then notes captured on GitHub for transparency.

The correct implementation for this feature (because I do agree this feature is needed), is to add a method to the `BHoM_Engine` which takes in arguments of `BHoMObject` and `IFragment`. The function should check whether a fragment already exists, and maybe, optionally, provide users the option to replace a fragment if a fragment already exists on the object.

This links in heavily to this issue: https://github.com/BHoM/BHoM/issues/478 which has not yet been resolved.

Therefore, if there is a block to the workflow the correct implementation is described above, and future implementation will want to check fragment attributes per the linked issue.
