### ISSUE TITLE
Architecture_Engine: Query Ceiling, Geometry

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1196]
#### Description:

Currently, we are missing `Query `for new elements we implemented `Ceiling `

1. `Query` Ceiling from BHoMObjects
2. `Query`  Polyline from Ceiling

**Comment by michaldengusiak** [comment]
1. correct
2. this will not work in Dynamo,
we need sth similar to physical... I will add one in next sprint
![image](https://user-images.githubusercontent.com/26113670/64850592-8ffaad80-d60d-11e9-93c4-0bae4f16471d.png)

**Comment by FraserGreenroyd** [comment]
You will be unable to add something similar for physical because the `Ceiling` object is defined by a `surface` geometry, not a `polyline` or `edges` which can be made into a `polyline` like `physical` objects.

If there is a bug with Dynamo preventing the `edges` from a `surface` being displayed then that is an issue for `Dynamo_Toolkit`. We don't want to overload the engines with duplicate methods which run the risk of confusing users.

**Comment by michaldengusiak** [comment]
1. yes, dynamo surface is one item Dynamo issue
_Warning: Query.GetProperty operation failed. 
Cannot implicitly convert type 'BH.oM.Geometry.PlanarSurface' to 'Autodesk.DesignScript.Geometry.Geometry'_
2. however we can provide a solution similar to what we have for the environment, physical
it behaves exactly the same way as wall or floor - all of them including ceiling is a `surface`
![image](https://user-images.githubusercontent.com/26113670/64852005-7313a980-d610-11e9-86f5-bdb3b4e6bfad.png)

**Comment by FraserGreenroyd** [comment]
The `Physical` objects make use of a `BH.oM.Physical.Elements.ISurface` whereas the `Architecture.Elements.Ceiling` make use of `BH.oM.Geometry.ISurface` for its geometry representation. If you take a look at the actual code [here](https://github.com/BHoM/BHoM_Engine/blob/master/Physical_Engine/Query/Polyline.cs) you will notice that we get the `polyline` by`physicalOpening.Location.Edges()` - as per the method described above.
Thus, we do not require an additional component for an `Architecture.Ceiling` when such methods already exist. The bug fix for Dynamo is the biggest thing needed which I can see an issue is now raised for so that's all good :smile:
