### ISSUE TITLE
Physical_Engine: Query Physical object by Name

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Engine#1211]
#### Description:

Allow to get Physical by Name

**Comment by FraserGreenroyd** [comment]
This will be superseded by the work of @awakeman in exposing LINQ components within BHoM UIs. This will allow us to pass a collection of objects, a property to search by, and the search term, which will allow this to be done.

Issues for that already exist, so this issue is being closed in favour of them.
