### ISSUE TITLE
Structure_Engine: PlasticModulus fails for some strange but valid sections

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#1503]
#### Description:

For example ISections with flange width == web thickness, 0-length line segements are added. The section integration should be able to handle this.

#### Test file(s):

https://burohappold.sharepoint.com/:f:/s/BHoM/EoIRVsIVmWRJkf0pFji8dWgBypRbqxrcfmRUh_cNzC2rng?e=zqJTtv

**Comment by kThorsager** [comment]
This is due to the `WetBlanketInterpetation` failing, causing that area to be much lower than the real area. And as finding half of the true area of the `Polyline` is how it finds the neutral axis it does cause a failure as the are no longer close to each other.

I'll fix it by removing the short segments in the beginning of `WetBlanketInterpetation` (which should have been done from the start)
