### ISSUE TITLE
 Architecture_Engine: Create CleanRoom method to clean room perimeter

### ISSUE THREAD

**Issue by BingWangUS** [BHoM/BHoM_Engine#1611]
#### Description:

Similar to the CleanPanel method in Environment_Engine.
Functions within the method:
remove vertices
simplify curves
recompute edges

**Comment by FraserGreenroyd** [comment]
`CleanPanel` Does not sit within the Geometry_Engine, it sits within the Envirionment_Engine.

The method can not be changed to accept a `Room` object because it needs to clean panel objects still.

I would advise we change this to be a new feature of the Architecture_Engine, as Room objects are Architecture objects, and just make a new method there rather than modify an existing method in the Environment Engine.
