### ISSUE TITLE
Geometry_Engine: Refactor Extend's public/private methods for compliance

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM_Engine#1741]
#### Broken rules:

https://github.com/BHoM/BHoM_Engine/pull/1709#issuecomment-624069117
https://github.com/BHoM/BHoM_Engine/blob/6d245c872e30fe60bf92db364aca28ad8f475a74/Geometry_Engine/Modify/Extend.cs#L72-L75
A modify method should return itself

#### Suggestions to restore compliance:

Either:
- brodining the scope of modify to include `ICurve` as valid
- Removing that boolean option and reference people to that method. `ExtendTanget`
- Move this and perhaps all `Extend` methods to `Compute`

FYI @pawelbaran @FraserGreenroyd 

### EDIT: Summary
Extend `Arc` by tangent is conceptually a modify, but object-wise a compute (does not return `Arc`). Favoured suggestion is to make the methods called by `IExtend` `private` to keep the method in modify and always return what you provide (`ICurve`)

**Comment by pawelbaran** [comment]
Hmm @LMarkowski am I correct that you have had a few iteration on that one? Personally I would say move it to `Compute` - if it works, it does not hurt 🙊

**Comment by LMarkowski** [comment]
Yeah, I remember discussing that one.
I don't think that dividing `Extend` and `ExtendTangent` would resolve this issue because we would still have to decide where to put `ExtendTangent` and I think dividing them between two namespaces would be strongly unintuitive.
I am also not a big fan of moving it entirely to `Compute` as the issue concerns only `Arcs` and `Extend` sounds strongly like a modifying method. But as I assume that broadening the scope of `Modify` isn't really on the table I would go with moving to `Compute`.

**Comment by pawelbaran** [comment]
Looking at @LMarkowski clear explanation, I strongly agree - splitting into 2 separate methods in 2 classes is unintuitive, `Modify` seems to be the natural habitat for this one. But for the sake of compliance, I would go for Moving all to `Compute`.

**Comment by FraserGreenroyd** [comment]
We shouldn't move things just for the sake of compliance, rather, we should work out why we can't follow the compliance rules with them in modify.

I don't understand at all from this discussion why an extended arc must return an ICurve and not an Arc?

**Comment by LMarkowski** [comment]
@FraserGreenroyd, It is because when you extend `Arc` with tangent lines it becomes line-arc-line `PolyCurve`

**Comment by kThorsager** [comment]
If the arc is extended along it's tangent it becomes a `polycurve` as an arc can't have straight segments.

![image](https://user-images.githubusercontent.com/53530468/81164178-d7acbb80-8f87-11ea-8762-a3f3e84a5cd6.png)

**Comment by FraserGreenroyd** [comment]
@LMarkowski @kThorsager ok in that case my next question is, if we have extended the arc and created a line-arc-line, have we modified the original arc at all? It would appear not, because now we have something which is invalid as an arc and is no longer capable of being represented as such.

Which would suggest we cannot modify an arc in this manner and it would be better to either:

A) Move that one method to compute and highlight it is not a modification but a new curve coming out
or
B) Remove the method and give an error saying `sorry, but arcs cannot be extended and still be arcs`.

Obviously B isn't really a viable option because the function of this method is useful (or it wouldn't have been written), but I disagree with moving the entire class up to compute just because of one problem in arcs.

**Comment by pawelbaran** [comment]
@FraserGreenroyd I get your point, but cannot imagine:
A) moving a single method (for `Arc` only) to `Compute` sounds very unintuitive from the user's point of view + it will cause issues with dynamic casting (?)
B) as you explained

I would prefer keeping all methods inside a single class - not sure if `Compute` (compliant) or `Modify` (sensible).

**Comment by FraserGreenroyd** [comment]
I feel like the conversation might be getting bogged down by the existence of the other methods.

The other methods though are fine, they are taking in a curve of their type (polyline, line, etc.) and returning a modified version of the same curve.

But arc isn't, because arc can't be extended without breaking the rules of being an arc (according to my understanding from @LMarkowski explanation), so it's not modifying anything. It's creating (or computing) a new curve entirely.

Let's say we had no extends method at all. And we wanted to make one for Arc. Where would we put it, based on the guidance for the placement of methods. To me, arc would fall into compute, because it fails to modify the existing arc but produces a new one.

But if we had no extends method and then wanted to add one for a line, that would make sense to have in modify because the original line is being changed (modified).

Maybe a different question. If the arc is not being extended (which it isn't because it ends up with straight line segments) then what is happening? We aren't extending the arc (so calling the method extends would be wrong), but maybe we can name the method after a different operation that is closer to what it is doing?

**Comment by pawelbaran** [comment]
Well, tangent extension is still extension in my understanding 🙊 And again, flipping the question: what if I put `Extend` of `Arc` in `Compute` and all others in `Modify`, and then want to run `IExtend`?

Btw, if I were mean I would argue that each method creates a new curve as we follow immutability principle :>

**Comment by IsakNaslundBh** [comment]
I would be on the side of seeing this as a modify method as well. you get something in, you do something with it and return it back. For the Arc case, the actual type will have to be changed for general cases, but its general stance of being a curve has not.

We have other cases like this in Geometry_Engine in particular where the input type might change, where the returned item is clearly a modified version of the input value, hence should be a modify (see transforms for arc, circles and ellipse).
Would strongly argue these should stay in modify as is, as it would be nonsensical to start moving to much stuff to compute simply for compliance reasons, and would argue the same for the extend case.

Then, with regards to how to resolve this, and suggestions:
1. Moving to compute (would be against this for reasons above)
2. Broadening the scope of compliance - Would not be against this if it could be done in a way that the rules are still clear
3. Making the incompliant methods private. This way the only way you could extend the arc would be via the interface method, which to some extent would make sense, and also follow what happens. You send in a **curve,** you get a modified version of that **curve** back. (as opposed to sending in an arc and getting an arc back)

IMO, ideal would be if we could update the compliance in a _clear easily explainable way_ that allowed the current code to stay as is, but think this could be hard. If that does not work or can be seen acceptable, I would vote for option 3, simply making the methods private.

**Comment by pawelbaran** [comment]
@IsakNaslundBh's idea of making methods private makes sense as a non-harmful solution. However, it sounds a bit like hiding the problem for the pure sake of compliance (if we do this to `Extend`, why not hide _all_ non-interface methods?).

This rings an alarm in my head - compliance should help us keep the code well structured and neat, but in this case it does not make things any neater, it only forces us to hide what we consider a problem based on current compliance assumptions.

**Comment by FraserGreenroyd** [comment]
At risk of derailing anything, first and foremost I can agree and support item 3 of @IsakNaslundBh suggestions as being the most logical for this particular issue, and would recommend that above moving the methods to compute.

Secondly, for hiding all non-interface methods, we [have discussed this before](https://github.com/BHoM/BHoM_UI/issues/125) and it was decided against (even by me, even though I now more closely support @IsakNaslundBh original point I think), but that is a topic we should perhaps pick up separately.

And then thirdly for the CI, also a point to pick up further separately but in brief notes here for reference, compliance regulations should be easy to follow, and have very clear paths to follow for meeting them. This is to aid new developers working with the framework, or aid people coming looking for things that they can expect how to find them/get used to what they're seeing (i.e. not too many major style differences jump out at them). In this particular case, the compliance is based on helping us to identify the difference between a modify method (something which alters the characteristics of an existing object) and a compute method, and a convert method, etc., etc., so this compliance rule is assisting us in keeping the code structured and neat. What we definitely don't want though is a 'one rule for one engine and one rule for another' approach because regulations must, by the spirit of their intention, be equal, fair, and crucially, consistent. So while we might feel Geometry_Engine deserves a little bit of a 'pass' on some compliance, it would then not be consistent, and risks confusion and the creation of black-boxes around parts of the code which is of course against the BHoM philosophy anyhow. Don't forget, the compliance regulations are discussed regularly (as per the wiki documentation), so they're never set in stone, but our default position should not start at "compliance is wrong let's ignore it". Instead we should do as we have done here - found something which is not compliant, and discussed it as a team with various options presented that allow the code to exist within the spirit of the regulations and not simply be a bit of red tape and move code to make it tick the boxes.

Which brings us to summarise the discussion that @IsakNaslundBh third point is the most appropriate solution in my mind all round. The allows the code to be compliant to the spirit of the regulations, it meets the rules of arcs, but still provides users the capacity to extend their arcs if they really want to.

So @kThorsager - I advise another change to the issue title and then go from there :smile:

**Comment by kThorsager** [comment]
Edited in a summary at the top which I hope isn't completely wrong

**Comment by pawelbaran** [comment]
I would still disagree (or at least feel very uncomfortable) with that as a code owner. Hiding particular methods only to meet compliance does not sound like the way to go - citing @FraserGreenroyd, it is exactly what I would call
> creation of black-boxes around parts of the code which is of course against the BHoM philosophy anyhow

Thinking about it yet again, I would opt for leaving the methods under `Modify` as an exception OR moving all to `Compute`.

<(am I starting to loop myself?)>

**Comment by pawelbaran** [comment]
Again, maybe the best way to go would be to leave the method as is for now and add it to the agenda of framework discussion? Looks like we have a few different points of view on this one.

**Comment by FraserGreenroyd** [comment]
> I would still disagree (or at least feel very uncomfortable) with that as a code owner. Hiding particular methods only to meet compliance does not sound like the way to go

Well I mean if we were being completely hard-line on it then we would remove the method for extending an arc and either move it to be housed separately in compute or not have it at all because, hard-line, the current method is not a modify. But I think we all agree that conceptually, it can be considered a modify, but does not conform to the regulations of a BHoM Modify method.

I mean if we wanted to get a little ridiculous I would question why don't we just change the definition for an arc instead to allow it to accept straight parts, which would then make the method compliant that way?

The reason we don't of course do that is cause the laws of Geometry are fairly fixed and we follow them. We could also question how this method ever got accepted into the engine in the first place - the modify rule is not new and has been in place in the wiki for a lot longer than the method.

So what we do instead is we compromise. We accept that the method should, conceptually, sit in the same file as the other methods. But I think we also agree that fundamentally, the method is not a strict BHoM modify method due to the laws of arcs. We also accept the functionality the method provides can be useful to users in certain instances. And thus, our compromise is, keep the method, to allow it to be used if necessary, but remove it from public gaze so that it can be both compliant, and sit in the file it conceptually should.

So I advise you go for uncomfortable rather than disagreeing :wink:

> Thinking about it yet again, I would opt for leaving the methods under `Modify` as an exception OR moving all to `Compute`.

I'm not open to the idea of exceptions (see previous, one rule for one concept) plus there is a risk of a slippery slope. I also think we all agree that conceptually 'compute' doesn't feel right for this particular set (though that said it is better than introducing exceptions).

> <(am I starting to loop myself?)>

Maybe 😄

**Comment by pawelbaran** [comment]
How can we speak of compromise when you are pushing _your_ solution that others disagree with, right after the proposal has been made to discuss it in a wider group? Just asking.

**Comment by FraserGreenroyd** [comment]
Ok so we're moving the discussion to a teams call shortly just to clear up any final items but to answer your last query @pawelbaran (cause I feel it is a valid query and worthy of a reply :smile: ), I believe I am doing a compromise because my initial gut feeling is to move the single arc method to compute and leave the others in modify due to the nature of their code. My compromise is to agree with @IsakNaslundBh suggestion point 3, because I can see how it benefits all the camps (compliance, concept, and desire). Hope that clarifies that point, and we'll see where we get shortly after the teams call :smile:

**Comment by kThorsager** [comment]
Following the discussion it was decided that this should be taken up at the next compliance call. 
With points such as:
- Compliance as warnings and/or blockers on PRs
- What is a `Modify`
- and more

As other annoying outliers exist such as `Transform` etc which do not belong in `Compute` but where their non-interface methods are very useful as public methods to avoid boiler plate type checking at use.

**Comment by FraserGreenroyd** [comment]
Having re-reviewed this issue in the historic issue review day today, I'm happy that we've likely resolved this via other mechanisms since the issue was raised/debated in 2020. As such, I'm closing this issue as no longer relevant for today's version of the BHoM 😄
