### ISSUE TITLE
Serialiser_Engine: Serialisation of objects fail if a Property has been overridden

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#1796]
#### Description:

If a virtual property on a base obejct, for example `Name` on the BHoMObject has been overridden, the object fail to serialise and deserialise. Might only be a problem with IImuttable objects, but needs to be investigated

#### Steps to reproduce:

Try overriding for example Name on an object and run to and from Json.

#### Test file(s):

Can be tested with

https://burohappold.sharepoint.com/:f:/s/BHoM/Esd8tkJZRzdAu30SbjtwfKwBppMw3IL5wEdOX1ddhQSCyg?e=cFuicU

while on the following branch: https://github.com/BHoM/BHoM/pull/879

**Comment by adecler** [comment]
> Might only be a problem with IImuttable objects, but needs to be investigated

Since I couldn't find conclusions on that point here on in the PR, I can confirm that it applies only to `IImmutable` objects. Take for example `BH.oM.Geometry.SettingOut.Grid` that override the `Name` property:

![image](https://user-images.githubusercontent.com/16853390/83478103-9268a480-a4c7-11ea-8dec-0330afa7707b.png)
