### ISSUE TITLE
Spatial_Engine: Create method GetEdges(IElement2D) which retrieves edges in a consistent manner, regardless of definition

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/BHoM_Engine#1873]
#### Description:
Currently, getting the external edges of a panel returns a myriad of different data types based on how the panel was defined. this could be a list of lines, list of curves, a single polycurve, or a list of polycurves/polylines. This results in errors downstream when these edges need to be computed. Instead, let's create a method which always outputs a list of outline segments in a consistent format- i.e. a flat list of lines/curves.

**Comment by kThorsager** [comment]
`OutlineCurve` in Spatial_Engine always returns a `PolyCurve` for any `IElement2D`

And while there technically aren't any safe guards angains a sub segment being defined as a polycurve/polyline it is unlikely as that would mess with a lot of other methods. (and hence one would change it)

Is this what you're looking for?

Otherwise there's also `ElementCurves` which returns the internal edges as well as segments

**Comment by JosefTaylor** [comment]
Awesome, that looks like it should do the trick, though I tested a bit, and it doesn't quite. I'll close this and raise a new issue for that.
