### ISSUE TITLE
Add geometry and set geometry for missing BHoM objects

### ISSUE THREAD

**Issue by JohannaOlin1** [BHoM/BHoM_Engine#2030]
Some objects that implement IElementXD do not implement their required extension methods for geometry manipulations. 

FYI @FraserGreenroyd and @IsakNaslundBh

**Comment by IsakNaslundBh** [comment]
Thanks @JohannaOlin1 . Would you mind listing the missing cases?

**Comment by FraserGreenroyd** [comment]
It turned out to be mostly Architecture Engine, Room and Ceiling - the others were actually fine when I re-read the Extension Method wiki page that you/Kalle produced. @JohannaOlin1 is currently working on adding them meticulously though throughout IElement1D and IElement2D elements so hopefully will be able to produce a list with the PR (as it's a live investigation) :smile:

**Comment by IsakNaslundBh** [comment]
@FraserGreenroyd I think Room at least should be covered by the IRegion interface I added last milestone. Not sure I added it to the Ceiling as well, but if it fits, would go that route instead, and let the Analytical_Engine take care of it for you.

**Comment by FraserGreenroyd** [comment]
Solved by #2032
