### ISSUE TITLE
Spatial_Engine: Check if element is on level

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#2054]
#### Description:

Check if an IElement is on a particular level, within a set max distance.

**Comment by IsakLarbornBH** [comment]
> Can we coordinate on that, I think this is one of those times when Environments has a similar method already perhaps - so good to have a chat if we can for our alignment 😄

I assume that you're referring to the `Environment.Query.Level()` method? It is similar, although it returns a Level, not a bool. It could perhaps be used the same way though, if it were modified to take any IElement, rather than just Panels. Either way I'm the new one here, I don't know what call to make 😄

**Comment by FraserGreenroyd** [comment]
> I assume that you're referring to the `Environment.Query.Level()` method? It is similar, although it returns a Level rather than a bool. It could perhaps be used the same way though if it were modified to take any IElement, rather than just Panels. Either way I'm the new one here, I don't know what call to make 😄

Don't let newness be a tool to not make a call, any call is a good call that can start a discussion :smile:

That was the method I was thinking of - in which case it could be good to refactor a little to make use of a new method from Spatial that returns a `bool` as you say, then our `Level()` query can call that to determine which level panels are on instead, that would work well with me.
