### ISSUE TITLE
Data_Engine: Remove use of CustomData in the code

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM_Engine#2072]
The files listed below have been detected as having code using `CustomData`. This detection has been automatic, and may have picked up on code comments or documentation. Please review each file carefully and remove all instances of `CustomData`.

This should be completed by the 30th October 2020.

<details>
<summary>Full list</summary>
<p>

 - [ ] BHoM_Engine\Data_Engine\Create\Table.cs

 - [ ] BHoM_Engine\Data_Engine\Query\ValuesAt.cs

 - [ ] BHoM_Engine\Data_Engine\Query\Linq\FilterBy.cs

</p>
</details>

**Comment by IsakNaslundBh** [comment]
The use of CustomData and ValuesAt is to map a unknown datarow to a custom object. Can change to dictionary there if that is more appropriate.

For the other side it is used to be able to generate a custom TableObejct. Same here, can change to dictionary.

Would argue though, that both those instances are using the custom data based on a custom obejct, with the intention of it being flexible and user driven rather than something that we are able to hardcode into some fragment.

@al-fisher @FraserGreenroyd @adecler any comments on this?

**Comment by al-fisher** [comment]
Agreed @IsakNaslundBh. This is correct use of CustomData/Objects.
Does not make sense to switch to dictionary - as you say. Dealing with unknown types/data is the purpose of CustomData - so all good I would say.
