### ISSUE TITLE
Diffing_Engine: Remove use of CustomData in the code

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM_Engine#2073]
The files listed below have been detected as having code using `CustomData`. This detection has been automatic, and may have picked up on code comments or documentation. Please review each file carefully and remove all instances of `CustomData`.

This should be completed by the 30th October 2020.

<details>
<summary>Full list</summary>
<p>

 - [ ] BHoM_Engine\Diffing_Engine\Compute\DiffWithCustomId.cs

 - [ ] BHoM_Engine\Diffing_Engine\Compute\DiffWithFragmentId.cs

 - [ ] BHoM_Engine\Diffing_Engine\Query\DifferentProperties.cs

</p>
</details>

**Comment by alelom** [comment]
I would keep all CustomData usages here. I will try to summarise the reasons.

### 1 Flexibility 
Originally, CustomData was used because AdapterId was stored there. Its usage was: "if the AdapterId of this object is the same of this other object you are comparing, then the two objects should be compared property-by-property". Now that it is put in fragments, the Diffing simply will rely on the data in the Fragment, which is a feature that was there already.

However, you (user) might still want to provide comparison information (some kind of ID) which is unrelated from any Adapter, and stored in CustomData. An example:
> a user has a list of objects. He assigns a progressive index to them to "recognise them" later.   
Then the user operates/modifies the objects, and in doing so the objects get shuffled somehow.  
The user then wants to compare the original vs the modified ones with diffing. 

In such a scenario, CustomData would hold a temporary Id used for this operation. In this sense, CustomData reflects a "volatile" storage of data. This index would not really represent an AdapterId or anything else, just something temporary defined by the User. I don't think a Fragment would be appropriate for this scenario, as it would feel more complex than it should be.

### 2 Code reuse
Now, the above covers the file `DiffWithCustomId.cs`.

`DiffWithFragmentId.cs` leverages the logic described above and included in `DiffWithCustomId.cs` to reduce code duplication. The id data is moved temporarily from Fragment to CustomData to use the same method. If we agree with the above, I would keep this usage too, otherwise we'd need to duplicate code.

Finally, the same reasoning to reduce code reuse applies to `DifferentProperties.cs`.

## Conclusion 
I would keep all usages of CustomData here.

**Comment by FraserGreenroyd** [comment]
I think that captures our discussions well @alelom, I'm happy for this issue to be closed based on that unless anyone has major objections :smile:
