### ISSUE TITLE
BHoM_Engine: Find fragment is not functioning from the UI

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#2211]
#### Description:

https://github.com/BHoM/BHoM_Engine/pull/2105 added another FindFragment method. Having two, with essentially the same method signature, makes non of them work in the UI, leading to pre-exisiting components to behave like this:

![image](https://user-images.githubusercontent.com/22005920/101070244-61af1800-359b-11eb-9bef-7998f8601917.png)

And adding a new component gives this, picking any of the two options:

![image](https://user-images.githubusercontent.com/22005920/101070526-c5394580-359b-11eb-9632-a65a0a7047ee.png)

![image](https://user-images.githubusercontent.com/22005920/101070626-deda8d00-359b-11eb-8548-ae83770536c8.png)

This is something that long term needs to be fixed in the UI but for now, think it needs to be fixed in the Engine.

#### Steps to reproduce:

try create a FindFragment method in a UI

#### Expected behaviour:

For the method do appear/deserialise

#### Test file(s):

Can not provide

**Comment by alelom** [comment]
Thanks guys, sorry about that. 
I believe I had added the method at some point in development because I wanted some method that ensured the return of an `IFragment`, or types derived from it. I must have dropped the need for that at some point because everything works fine without it. 
I think I should've solved that in the first place by adding `where T : IFragment` on the original method instead. If I encounter the need for that again I will make sure to bring it up with you and check that everything works. Thanks.
