### ISSUE TITLE
Geometry_Engine: Add Convex Hull method

### ISSUE THREAD

**Issue by sofmal** [BHoM/BHoM_Engine#238]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
As discussed with @IsakNaslundBh during our new weekly clear out of old issues, the method described above does actually exist in the Geometry_Engine and this issue was not closed.

However, we have discovered the method is in `create` when it should be in `compute` - this needs moving (with deprecation of the existing).
