### ISSUE TITLE
PlanarSurface is missing InternalElements2D

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#2380]
#### Description:

As in the title, `PlanarSurface` is missing `InternalElements2D` method, which means that calling `IElement2D.IInternalElements2D` on it returns an empty list and the failure is silent (or will be after #2378 gets merged). Another brick to the wall we are building around `RunExtensionMethod` @IsakNaslundBh @alelom 😃 

I am assigning a few individuals to make sure we are all in the loop - it seems that the pattern may need a wider discussion and careful tweaks.

**Comment by IsakNaslundBh** [comment]
`PlanarSurface` is not an `IElement2D` though. From memory, the issue here is the exact this reason why, so this is not really a bug but a missing feature. Makes me less worried about this, and less urgent IMO, even though we need to resolve it.

It needs to be handled by a slight restructuring of the Planar surface though, as the internalBoundaries right now are `ICurves`, and those can ofc not be `IElement2D`.
