### ISSUE TITLE
Geometry_Engine: IsCoplanar returns different results for the same points list with or without duplicated points

### ISSUE THREAD

**Issue by LMarkowski** [BHoM/BHoM_Engine#2423]
#### Description:

As in header. Coplanarity of points shouldn't depend on presence of duplicates. Might be the root of #2419 

#### Steps to reproduce:

See the test file.

#### Test file(s):

[SharePoint](https://burohappold.sharepoint.com/:f:/s/BHoM/EtT0QY6Sul1Mvtda3pIqLOcBz-Q-Nykq1yOJqxtAqpr6KA?e=pcFxe4)

**Comment by Tom-Kingstone** [comment]
After a lot of playing around, I think this is more an artefact of the order of the list of points, and how the numerical tolerance is calculated, than that there are duplicate points.

This issue likely happens due to floating point rounding errors (fun!), but I don't know enough matrix calculus to fix the issue (or even find where the issue actually stems from). 

My naïve approach is to set the tolerance for this method a bit lower.
Slightly less naïve might be to change the RowEchelonForm tolerance input to be the original tolerance, but keep CountNonZeroRows tolerance as REFTolerance.
