### ISSUE TITLE
Shall we consider setting up a framework for settings management?

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#2709]
#### Description:

Following the discussion that happened around https://github.com/BHoM/BHoM_Engine/pull/2648, I am wondering whether it would not be worth setting up a framework to manage the various BHoM-related settings that we store (or could store):
- loading settings on startup (existing BHoM_UI feature)
- storing settings in memory
- modifying the settings stored in the memory
- returning settings of requested type
- loading/saving settings in runtime
- saving the settings on shutdown

This could be done by expanding/leveraging the `ISettings` interface, i.e. on startup, for each type that implements the interface, `LoadOrInitialise` method gets triggered, resulting in a centrally stored collection of `ISettings`, one instance per type. Then, `GetSettings<T>` or `GetSettings(Type)` would return the relevant settings from the central storage, `SetSettings` would modify them etc.

The above description is of course very high level, with _centrally stored_ being the key blank spot I guess (it could be a static class or even a singleton etc.). However, before going into more details, I am curious whether that would be something others find useful at all.

**Comment by FraserGreenroyd** [comment]
Having had a quick chat with @alelom on this and discussed the issue with the dependency chain for where best to store this code.

The initial thought is obviously BHoM_Engine/Base_Engine project, because settings are going to be core to a lot of things that we do. However, loading up settings stored in JSON requires a dependency on Serialiser_Engine to effectively use existing code from there. This causes an issue, because Serialiser_Engine depends on Base_Engine for error recording, which means that Base_Engine cannot depend on Serialiser_Engine for serialisation.

Putting the methods within Serialiser_Engine also didn't seem to make much sense, as it would grow the scope of what Serialiser_Engine is then being asked to cover. There is also the potential for the settings configuration to grow, which may further bloat Serialiser_Engine if they were stored in there.

As such, for the time being, @alelom and I agreed it makes sense to make a new project for the settings to be housed, encapsulating the settings related code to one DLL which other projects can depend on if needed, and gives a home to the settings code to grow in the future as desired.

**Comment by FraserGreenroyd** [comment]
- [ ] loading settings on startup (existing BHoM_UI feature)
 - [ ] storing settings in memory
 - [ ] modifying the settings stored in the memory
 - [ ] returning settings of requested type
 - [ ] loading/saving settings in runtime
 - [ ] saving the settings on shutdown
