### ISSUE TITLE
MEP_Engine: Solid Volumes for List of Pipes and Ducts

### ISSUE THREAD

**Issue by alexissantella** [BHoM/BHoM_Engine#2743]
#### Description:

Add the ability to query lists of pipes and ducts for their solid volumes.

**Comment by michaelhoehn** [comment]
Just adding a bit of clarification from our conversation today on the issue. This specific has been identified as a result from using the current `SolidVolume()` methods within the Excel UI. Since Excel does not natively support lacing like Grasshopper does, there is a need for the current methods to have an alternative input supporting `this List<Duct> duct` instead of simply one duct at a time.

**Comment by michaelhoehn** [comment]
Closing this issue as a new prototypes space has been made available for use.
