### ISSUE TITLE
Geometry_Engine: Stop checking for SelfIntersections when computing normal for curves?

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#2797]
#### Description:

While doing some profiling on some of our heavier geometry methods such as the Boolean intersection/difference/union methods for polycurves/polylines it was found that the clear bottleneck in the execution of those methods was coming from the computation of the normal of the curves, and more specifically, the check if the curves where self intersecting.

for this case, this check is fundamentally redundant, and the method itself simply just raises a warning if the curve actually is self intersecting, but is only raising a warning.

Commenting this check out and re-running saw a performance boost of 80% (!!) for the test case I was running, which involved quite a lot of heavy operations, including computation of voronoi diagrams and similar, with time to compute going from 10 to 2 seconds by just this simple change.

Given this, I am tempted to remove this check from the method, alternatively add another method (something like UnsafeNormal or similar) that simply skips this check (and maybe some others) that can be called when the self intersection check simply is not required for the method to perform the way that is needed.

Glad to get any input on this.

@al-fisher @pawelbaran @FraserGreenroyd

**Comment by al-fisher** [comment]
Inclined to agree!
In terms of a performance hit for _"just"_ user feedback as a warning - this seems like something we should not be doing. Or at least have the option to not do. Especially due to this being such a low level method that can be called thousands of times in certain algorithms.

Would support removal of the check as is not a functional change (is simply removal of a warning message and the return value of the method has not possibility of being affected) but agree we should raise an issue to address a general solution to having alternative methods with various levels of checks (affecting return value) and warnings (giving user feedback) activated.
