### ISSUE TITLE
Library_Engine: Calling Query.Datasets outside UI returns DataSet with null Data

### ISSUE THREAD

**Issue by EnricoAntolini** [BHoM/BHoM_Engine#2842]
#### Description:

Context: this is needed to perform Converts in https://github.com/BHoM/Karamba3D_Toolkit.

We need to read SectionProperty datasets and match certain datasets with Karamba's datasets.

#### Steps to reproduce:

Calling this method from outside a UI, e.g. from a console application where all necessary dependencies are referenced:
```cs
var dataSets = BH.Engine.Library.Query.Datasets("HE");
```

returns a non-null Dataset object with a null Data property.

Note that the same line, if executed from a Component in Grasshopper, returns a valid Dataset with non-null Data property.

![image](https://user-images.githubusercontent.com/66356545/169867546-c1c31e62-dc05-4225-be29-9554ae00f468.png)

While this method is successful when invoked from a UI, development progress is sensibly slowed because we cannot invoke it from a Console App or a Unit Test project, and code cannot developed rapidly around it.

#### Expected behaviour:

DataSet should not have null Data property.

**Comment by IsakNaslundBh** [comment]
Hi @EnricoAntolini 

The reason this works in the UI but not in the particular Console app is most likely due to the console app not having all the required assemblies loaded.

The BHoM_UI makes a call to `BH.Engine.Base.Compute.LoadAllAssemblies();` among the first things it does when being started, which ensures that all BHoM assemblies in the C:\ProgramData\BHoM\Assemblies folder are loaded up. Making the same call in the console app should hopefully resolve this issue.

Another way that should be working is to ensure that the Console App has _all_ the right required references for the data in the particular Dataset. For the SectionProperties, such as HE, that means Structure_oM and all of its dependencies. If they are all referenced and accessible for the Console App, it also should be able to de-serialise the dataset.


We could have a look into making the Library_Engine call `BH.Engine.Base.Compute.LoadAllAssemblies();` before trying to parse the first assembly, but would prefer to not enforce this if possible.

**Comment by alelom** [comment]
We solved this problem by:
- Referencing BHoM via local DLLs only:
  - Removing references to Nuget packages. The theory is that nuget packages in the console app project may have clashed with other local references in other project.
  - Re-creating the project. This may or may not have weighted to an extent - the Visual studio Modules windows seemingly showed that, despite removing nugets, the referencing assemblies were coming from something similar to the local nuget folder.
- Compiling the BHoM_Datasets toolkit, therefore undoing some formatting that was mistakenly done to the .json files of the datasets (formatting the .json dataset file breaks the deserialization!)
