### ISSUE TITLE
Spatial_Engine: no taper flange angle sections

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/BHoM_Engine#288]
We here in the backwards US of A use taper flange channels almost exclusively, vs. parallel flange channels. We also still occasionally run into S shapes (tapered flange I beams). What's the best way to support and serialize these?

**Comment by FraserGreenroyd** [comment]
As there are now create methods for taper flange profiles within the Spatial_Engine, which has been introduced since this issue was raised, I am marking this issue as closed as hopefully the developments undertaken since 2018 have suitably addressed this. If anyone feels this isn't the case however, please feel free to reopen 😄
