### ISSUE TITLE
BHoM Environment Panels from BREP failed to run properly

### ISSUE THREAD

**Issue by charliebrookerBH** [BHoM/BHoM_Engine#3096]
#### Description:

Panels from BREP sometimes fails to produce panels from input BREPs. 

![image](https://github.com/BHoM/BHoM_Engine/assets/26814591/e09f62e8-bb6b-4d34-957f-cec9e7e410af)

Input BREPs
![image](https://github.com/BHoM/BHoM_Engine/assets/26814591/ad7ad8f6-2e22-4585-a4ba-950629d7d49a)

Output Panels
![image](https://github.com/BHoM/BHoM_Engine/assets/26814591/9c14a6da-90c6-4ff6-a915-010c16f63105)

As a workaround, using Edges works as expected
![image](https://github.com/BHoM/BHoM_Engine/assets/26814591/60db02b4-5257-47c6-af49-24c7061274a5)

#### Steps to reproduce/Test file:

Example geometry in this file.
[ExamplePanelsFromBREPsError.zip](https://github.com/BHoM/BHoM_Engine/files/11871723/ExamplePanelsFromBREPsError.zip)

**Comment by FraserGreenroyd** [comment]
Improvements have been made to the error reporting for users. On investigation of this issue, #3142 was found to be needed. Extracting data using `NurbSurface` isn't supported within the Environment_Engine at this time because the necessary methods aren't supported within `Geometry_Engine` (one for @IsakNaslundBh or @alelom at some point). This means creating panels from that geometry isn't possible - but better error messages have been provided to try and help the user navigate this and use other workarounds as appropriate.

#3142 addresses the missing fall back option, which resolves some of the exceptions being thrown.
