### ISSUE TITLE
Serialiser_Engine: Object of type System.DBNull cannot be serialised.

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/BHoM_Engine#3210]
#### Steps to reproduce:

See script below - you may need to switch scripts to prompt the error (which I suspect is a UI issue from the `Explode` component).

Note the script below relies on the following PR:
https://github.com/BHoM/BHoM/pull/1560

#### Expected behaviour:

No error message stating: 

> 1. Object of type System.DBNull cannot be serialised.

 Worth noting this appears to be a visual issue as the component explodes and the information is present.

#### Test file(s):

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Engine/Serialiser_Engine/%233210-DBNullCannotBeSerialised.gh?csf=1&web=1&e=QubDWM - data here is internalised to produce a concise script, but originally came from a `Pull` component.

**Comment by FraserGreenroyd** [comment]
@peterjamesnugent probably best to assign myself as well as @adecler to Serialiser Engine issues for visibility as both of us can support on issues in that regard 😄

**Comment by Tom-Kingstone** [comment]
I have seen this issue happen before when I was dealing with a list of ~ 20,000 panels.
The error also appears when a different gh component is deleted.

When running with a debugger attached to Rhino, and a breakpoint on the `else` on the private fallback for [`Compute.Serialise`](https://github.com/BHoM/BHoM_Engine/blob/develop/Serialiser_Engine/Compute/Serialise.cs), it seems the serialiser is being given an empty BSON document instead of null, with type System.DBNull (as already noted).
A possible solution would be to handle the case where `value.GetType() == typeof(System.DBNull)`, though I would really like to know where the null is coming from!

**Comment by Tom-Kingstone** [comment]
Info for how to recreate:
- Get a BHoM component with more than 20,000 objects as an output.
- Place a second BHoM component
  - must be a BHoM component
  - must have at least one input that does not have a default.
- Delete the second component
- System.DBNull appears on component with large number of objects

**Comment by FraserGreenroyd** [comment]
> * System.DBNull appears on component with large number of objects

Have you checked if it happens on components with smaller numbers of objects as well? I suspect it might be that the error is picked up by the last component that runs and catches the error itself rather than it being linked to having a large number of objects? That is just a thought in my head though so may not be true, but would be good to definitively rule it out if we can

**Comment by Tom-Kingstone** [comment]
of note: the error is raised even if there isn't a large component, but does not display on anything

**Comment by Tom-Kingstone** [comment]
System.DBNull seems to be coming from [`BH.UI.Base.Caller.SetInputs`](https://github.com/BHoM/BHoM_UI/blob/develop/BHoM_UI/Caller/SetInputs.cs)
