### ISSUE TITLE
Geometry_Engine: Add HashArray method for core geometry types

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#3264]
#### Description:

As in the title, `HashArray` seems to be missing for a few core geometry types:
- `TransformMatrix`
- `Cartesian`

**Comment by alelom** [comment]
The reason why we didn't add GeometryHash for many geometric types is because we thought it would never get used with them. In particular, we added support for "non-conceptual" types: everything except Vector, TransformMatrix, Cartesian, and probably a few more. Anyways, it can make sense, for completion's sake, to add support for all.

**Comment by pawelbaran** [comment]
Yes, I see immediate use for transforms, so definitely worth adding 👍
