### ISSUE TITLE
Geometry_Engine: Fix DiscontinuityPoints for PolyCurve

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#392]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
Having examined the historic [test script](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/Archive/BHoM_Engine/Geometry_Engine/Query/[DiscontinuityPoints.gh](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/Archive/BHoM_Engine/Geometry_Engine/Query/DiscontinuityPoints.gh?csf=1&web=1&e=VvjW1g)?csf=1&web=1&e=VvjW1g) and investigated the 4 failing `Polycurve` items individually, it appears that the issue lays in the test script generation of the data. Manual inspection of the test data reveals an extra control point however, 19/20 of the tests pass, and no one has reported any issues since 2018 when this issue was first raised. As such, I'm closing this issue as stale for now.

Additionally, we also have [data-driven unit-tests](https://github.com/BHoM/BHoM_Engine/blob/develop/.ci/Datasets/Geometry_Engine/Query/DiscontinuityPoints.json) for `DiscontinuityPoints` which further checks the methods to the latest standards for BHoM.

If anyone comes across additional information however, please feel free to reopen 😄
