### ISSUE TITLE
Geometry_Engine: Write teh test for the Query.IsClockwise methods

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#400]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
This issue has since been handled in other issues, as evidenced by the [existence of data-driven unit-tests](https://github.com/BHoM/BHoM_Engine/blob/develop/.ci/Datasets/Geometry_Engine/Query/IsClockwise.json) for the `IsClockwise` methods, so I'm closing this issue as historic and stale, but also as completed 😄
