### ISSUE TITLE
Structure_Engine: Load object constructors need 'ids' inputs as an alternative to 'objects'

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM_Engine#484]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
Having reviewed this historic issue and the code base, and taking into account the time that has passed since the issue was raised, it appears that the issue has been superseded by other developments around the loads done by @IsakNaslundBh and the team in the intervening years since the issue was originally raised.

As such, I'm closing this issue as stale today, however, if anyone disagrees and can point out bits I've missed (which I'm sure I have!) then please feel free to reopen 😄
