### ISSUE TITLE
Geometry_Engine: Some Interface method do not have recognised interface as first parameter

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#499]
Here's the list:

 - BH.Engine.Geometry.Compute.ISortAlongCurve(List,ICurve)
 - BH.Engine.Geometry.Query.IIsContaining(BoundingBox,Point)
 - BH.Engine.Geometry.Query.IDistance(Point,ICurve)

**Comment by FraserGreenroyd** [comment]
Having reviewed this historic issue and discussed with both @adecler and @al-fisher , the following points are noted.

 - `IIsContaining` is fine and  does not contain inputs which aren't interfaces for their first input anymore, so this has been resolved since the issue was raised.

Both `ISortAlongCurve` and `IDistance` take in a `List` or `Point` as their first input respectively, but their second input is then an `ICurve`, with the none-I methods (standard `SortAlongCurve` and `Distance`) being implemented for each individual type of curve supported by BHoM.

As such, the interface method is there to support users plugging in any curve type to an `IDistance` method with their point. Semantically, whomever wrote the original methods opted for the `Point` input to take precedence, which discussion has supported as being correct.

Therefore, the remaining I methods for `ISortAlongCurve` and `IDistance` are deemed to be ok and compliant to current BHoM standards for 2024, so this issue is being closed on that basis 😄
