### ISSUE TITLE
Structure_Engine: DepthAt and WidthAt failing

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#527]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
After viewing this historic issue and associated test scripts, it is not possible to identify what the failures were/are with the methods. As the methods have undergone work since this issue was raised, it may be possible that bugs have been fixed in other issues. As such, I'm closing this issue for now, with a view that if any future issues exist with these methods, then they can be raised as new issues with updated test scripts as appropriate 😄
