### ISSUE TITLE
Structural_Engine : Agree common BHoM naming conventions for SectionProfiles

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_Engine#651]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
As this issue has not been revisited since 2018, and further developments have been made to the section profiles in the intervening time, I am closing this issue as stale as part of our historic issue review.

If anyone in the US would like us to revisit this issue if it has not been resolved satisfactorily then please feel free to reopen 😄
