### ISSUE TITLE
Structure_Engine: Add description documentation on an area of the engine

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#665]
Add Description, Input and Output attributes to all methods in the Structure_Engine

**Comment by FredericBourgeon** [comment]
@IsakNaslundBh Do you mean something similar to what is done on [BHomObjects.cs](https://github.com/BHoM/BHoM_Engine/blob/05bfd768bf544899d6ddd60795d3b81b551538b2/Engine_Explore/BHoM/Base/BHoMObject.cs)?

**Comment by al-fisher** [comment]
Hey @FredericBourgeon I think this issue is refering to the in-code documentation attributes see wiki page here: https://github.com/BHoM/documentation/wiki/Code-Attributes

In particular the [Description](https://github.com/BHoM/documentation/wiki/Code-Attributes#description), [Input](https://github.com/BHoM/documentation/wiki/Code-Attributes#input) and [Output](https://github.com/BHoM/documentation/wiki/Code-Attributes#output)

I would suggest raising sub-issues tackling specific sections/collections of methods in the Structure_Engine - to do this batches 😄

**Comment by FredericBourgeon** [comment]
Refer to the following issues for detailed tracking:
- [ ] #1179
- [ ] #1180 
- [ ] #1181 
- [ ] #1182

**Comment by IsakNaslundBh** [comment]
https://github.com/BHoM/BHoM_Engine/pull/1547 closes this
