### ISSUE TITLE
Serialisation_Engine : Enabling backwards compatibility for deserialisation of previous oM versions

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_Engine#779]
This idea has definitely been discussed previously - but @IsakNaslundBh raising as new issue now as very relevant to chats today. @adecler @IsakNaslundBh @epignatelli can you comment on the below?

Essentially can we start now to implement the ability to automatically deserialise objects that were serialised in a previous version of BHoM? Converting from v2.1 to v2.2 say. This will naturally hugely limit impact of breaking changes as we continue to refine and make necessary changes to object model properties etc.

In the context of the current proposed changes to the Node object - automatically parsing the version 2.1 Json to new latest version 2.2 Json by using the explicit cast of `Point` to `CoordinateSystem` could work?

Would we then have overloaded `Convert.FromJson` methods which allow additional arguments to control version to convert from?
``` C#
Convert.FromJson(string json, System.Version version)

```
Thoughts?

**Comment by adecler** [comment]
Referencing #302 as it is quite relevant in this context.

**Comment by adecler** [comment]
As discussed, this can be handled in two steps:
- Do the universal default converter to CustomObject as mentioned in #302.
- Create a Versioning_Engine That will be called by the deserialiser when it fails to get the BHoMObject back from json/bson.

A few more details on the versioning engine for reference:
- Central interface method that takes a custom object as input and takes care of finding and executing the (sequence of) method(s) necessary to get the object in its latest format.
- All the conversion methods will take a CustomObject and return a CustomObject. That way the final custom object can be turned back into the final BhoM object by a single generic method.
- The conversion methods themselves are the only thing that have to be written by the BHoM contributors (one method per breaking change). That is it. The central dispatcher method will take care of the rest in a generic way.
- The conversion methods can be mined when the dll is loaded and stored in a dictionary where keys are strings representing the type (the same string as the one already in json for the `_t` property) and each value is a list of conversion methods listed in their chronological order (so that we can convert from any version X to any version Y by iterating through those methods).
- Repeating things here but this is why al lthe conversion methods are taking Custom object in and return custom objects. So they can be chained, with the final conversion to BHoM taken care of by a generic converter from custom to BHoM.
- On the side of the Deserialiser (Serialiser_Engine), it is very little code since it just always create a custom object when fails and gives a chance to the versionning engine to give back something more up to date before giving up for good (i.e. returning a custom object)

Disclaimer: this is just a quick mind dump after a long day so I hope this is actually making a bit of sense.
