### ISSUE TITLE
Reflection_Engine: Provide a way to find the lowest common shared type between a list of types

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Engine#780]
Given a `BH.oM.Geometry.Point` and a `BH.oM.Geometry.Polyline`, I expect to get `BH.oM.Geometry.IGeometry`

**Comment by FraserGreenroyd** [comment]
Capturing the discussion from #781 when this was first attempted, it seems that we want/need an ability to obtain all the inherited types for a given type (an update to `InheritedTypes.cs`), and then from that, ascertain the lowest shared type between two types (the original intent for this issue).

So to close out this issue, it appears that we need to do the following:

 - Update `InheritedTypes.cs` to include an option for getting all inherited types
 - Add a method to obtain inherited types at a given level (e.g. immediate inheritance, inheritance via another type - linked to this: https://github.com/BHoM/BHoM_Engine/pull/781#discussion_r251800957 whereby `C : B` and `B : A` - being able to obtain `A`  and obtain that it is a level removed from `C`.
 - Add method to get lowest common base type between two given types

**Comment by FraserGreenroyd** [comment]
Following an attempt to resolve this today, I think this is not an issue that can be solved easily, nor is worth doing given the lack of need since 2019.

The issues that I have found are as follows:

 - All objects which inherit from `BHoMObject` implement `IBHoMObject` and `IObject` at their base level - so `type.GetInterfaces()` returns both of these common types at the initial level, and the [remarks for .Net6 and lower](https://learn.microsoft.com/en-us/dotnet/api/system.type.getinterfaces?view=net-7.0#remarks) indicate the order of the types is random and cannot be relied on
 - Thus obtaining `IGeometry` is not as simple as looking at the first inheritance level and finding a matching type, as either `IObject` or others may be found before the lowest level.
 - Filtering by assembly or namespace isn't viable - how do we rank the assemblies such as Dimensional and Analytical? Should 1 take priority over the other? I don't think either should, thus finding the lowest common type between say a `BH.oM.Environment.Elements.Panel` and `BH.oM.Structure.Elements.Panel` becomes tricky again, because both `IPanel` and `IElement2D` would be valid, but how would we rank them?
 - It is not currently possible to obtain interfaces only implemented by the object and not something in its inheritance chain, as C# compilation resolves everything down, thus an object that implements `IBHoMObject` is compiled as `public class Foo : IBHoMObject, IObject` even if the class definition is only `public class Foo : IBHoMObject`
 - Filtering based on "could another interface provide the interface" also isn't helpful, because many objects implement interfaces as a tagging system (per BHoM philosophy). For example, an [Environment Panel](https://github.com/BHoM/BHoM/blob/develop/Environment_oM/Elements/Panel.cs) object implements both `IPanel` and `IElement2D` in its definition, so simply stating that `IElement2D` can be obtained from `IPanel` wouldn't help find a lowest common interface because we might put `IElement2D` higher than it is actually declared

As a result, due to this issue not being required for 4+ years, and the complexity involved in solving it with our current frameworks and options available, I'm closing this issue as a will not resolve, because I do not feel it is worth the energy expended to resolve it for BHoM needs. Please reopen if anyone disagrees 😄

**Comment by FraserGreenroyd** [comment]
There is also [this method](https://github.com/BHoM/BHoM_Engine/blob/develop/Reflection_Engine/Query/CommonBaseType.cs) should anyone need something as well 😄
