### ISSUE TITLE
Structure_Engine: ControlPoints(Panel) returns duplicate points for polycurve edges

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/BHoM_Engine#977]
when the edges of a panel are a list of edges, rather than an edge containing a polyline curve, ControlPoints returns twice as many points as it ought to.

**Comment by peterjamesnugent** [comment]
@JosefTaylor to review if it is still an issue and replan.

**Comment by IsakLarbornBH** [comment]
This doesn't happen when using the ControlPoints(IElement2D) method in Spatial_Engine, however that one still duplicates one point since it doesn't consider whether the curve is closed or not.

Why does there need to be a separate method for Panels anyway? My first thought was to handle openings, but the IElement2D method seems to handle openings just fine. Deprecate and redirect?

**Comment by IsakLarbornBH** [comment]
Well, @IsakNaslundBh is way ahead of me on that one, with ControlPoints in Structures_Engine about to be deleted once #2146 gets merged. Should probably fix ControlPoints in Geometry_Engine so it can handle closed curves then.

**Comment by IsakLarbornBH** [comment]
Having a look through my old assigned issues - closing this as it was fixed by #2146 as far as I can tell.
