### ISSUE TITLE
Geometry_Engine: PolyCurve methods do not cover a case with one SubPart being a circle

### ISSUE THREAD

**Issue by LMarkowski** [BHoM/BHoM_Engine#980]
Some PolyCurve methods are written for elements consisting of lines and arcs only. If PolyCurve has only one curve and it's a circle they return nulls or throw errors.

I.E. It caused #902 which was fixed in #979. SplitAtPoints also has this issue

**Comment by IsakNaslundBh** [comment]
This is now really old, and issue does not state which methods that are of concern, only methods that already have been identified and fixed in another issues/PR.

Will close this, and if problem described shows itself in other methods, a new issue targeting that method explicitly is to be raised and handled instead.

**Comment by IsakNaslundBh** [comment]
@pawelbaran please shout if you disagree
